spring:
  application:
    name: rabc-demo
  data:
    mongodb:
      uri: mongodb://admin:123456@1.14.93.107:27017/form?authSource=admin
  datasource:
    url: jdbc:mysql://1.14.93.107:3306/rabc_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql262715
  redis:
    host: 1.14.93.107
    port: 6379
    database: 0
    timeout: 1800000
    password: redis262715
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 0
        min-idle: 0
# OSS相关配置信息
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI5tKXq9aPyK6ne5DZXnom # 访问身份验证中用到用户标识
    accessKeySecret: S46m8qshPER5gruLLlpAPzv7jjPfF4 # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: mhw-oss # oss的存储空间