spring:
  application:
    name: rabc-demo
  datasource:
    url: jdbc:mysql://1.14.93.107:3306/rabc_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql262715
  redis:
    host: 1.14.93.107
    port: 6379
    database: 0
    timeout: 1800000
    password: redis262715
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 0
        min-idle: 0